-- MySQL Script generated by MySQL Workbench
-- Mon Mar 18 07:23:41 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema serpabooksdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema serpabooksdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `serpabooksdb` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `serpabooksdb` ;

-- -----------------------------------------------------
-- Table `serpabooksdb`.`autor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `serpabooksdb`.`autor` (
  `id_autor` BIGINT NOT NULL AUTO_INCREMENT,
  `nm_autor` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id_autor`))
ENGINE = InnoDB
AUTO_INCREMENT = 312
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `serpabooksdb`.`info_livro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `serpabooksdb`.`info_livro` (
  `id_info_livro` BIGINT NOT NULL AUTO_INCREMENT,
  `titulo_livro` VARCHAR(255) NULL DEFAULT NULL,
  `nota_livro` FLOAT NULL DEFAULT NULL,
  `idioma_livro` VARCHAR(255) NULL DEFAULT NULL,
  `resumo_livro` VARCHAR(500) NULL DEFAULT NULL,
  `sinopse_livro` VARCHAR(5000) NULL DEFAULT NULL,
  `id_autor` BIGINT NOT NULL,
  PRIMARY KEY (`id_info_livro`),
  INDEX `fk_info_livro_autor_idx` (`id_autor` ASC) VISIBLE,
  CONSTRAINT `fk_info_livro_autor`
    FOREIGN KEY (`id_autor`)
    REFERENCES `serpabooksdb`.`autor` (`id_autor`))
ENGINE = InnoDB
AUTO_INCREMENT = 208
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `serpabooksdb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `serpabooksdb`.`usuario` (
  `id_usuario` BIGINT NOT NULL AUTO_INCREMENT,
  `nm_usuario` VARCHAR(255) NULL DEFAULT NULL,
  `dt_nascimento_usuario` DATE NOT NULL,
  `login_usuario` VARCHAR(255) NULL DEFAULT NULL,
  `senha_usuario` VARCHAR(255) NULL DEFAULT NULL,
  `role_usuario` TINYINT NULL DEFAULT NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `serpabooksdb`.`avaliacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `serpabooksdb`.`avaliacao` (
  `id_avaliacao` BIGINT NOT NULL,
  `id_usuario` BIGINT NOT NULL,
  `id_info_livro` BIGINT NOT NULL,
  `ds_avaliacao` VARCHAR(255) NULL DEFAULT NULL,
  `dt_avaliacao` DATETIME NULL DEFAULT NULL,
  `valor_avaliacao` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`id_avaliacao`),
  INDEX `fk_usuario_has_info_livro1_idx` (`id_info_livro` ASC) VISIBLE,
  INDEX `fk_usuario_has_usuario1_idx` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_has_info_livro1`
    FOREIGN KEY (`id_info_livro`)
    REFERENCES `serpabooksdb`.`info_livro` (`id_info_livro`),
  CONSTRAINT `fk_usuario_has_usuario1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `serpabooksdb`.`usuario` (`id_usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `serpabooksdb`.`capa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `serpabooksdb`.`capa` (
  `id_capa` BIGINT NOT NULL AUTO_INCREMENT,
  `ds_capa` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id_capa`))
ENGINE = InnoDB
AUTO_INCREMENT = 20
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `serpabooksdb`.`editora`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `serpabooksdb`.`editora` (
  `id_editora` BIGINT NOT NULL AUTO_INCREMENT,
  `nm_editora` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id_editora`))
ENGINE = InnoDB
AUTO_INCREMENT = 178
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `serpabooksdb`.`livro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `serpabooksdb`.`livro` (
  `id_livro` BIGINT NOT NULL AUTO_INCREMENT,
  `url_imagem_livro` VARCHAR(255) NULL DEFAULT NULL,
  `numero_paginas_livro` INT NULL DEFAULT NULL,
  `dt_publicacao_livro` DATE NULL DEFAULT NULL,
  `dt_cadastro_livro` TIMESTAMP NULL DEFAULT NULL,
  `isbn_10_livro` VARCHAR(255) NULL DEFAULT NULL,
  `isbn_13_livro` VARCHAR(255) NULL DEFAULT NULL,
  `id_editora` BIGINT NULL DEFAULT NULL,
  `id_capa` BIGINT NOT NULL,
  `id_info_livro` BIGINT NOT NULL,
  PRIMARY KEY (`id_livro`),
  UNIQUE INDEX `isbn_10_livro_UNIQUE` (`isbn_10_livro` ASC) VISIBLE,
  INDEX `fk_livro_editora1` (`id_editora` ASC) VISIBLE,
  INDEX `fk_livro_capa1` (`id_capa` ASC) VISIBLE,
  INDEX `fk_livro_info_livro1_idx` (`id_info_livro` ASC) VISIBLE,
  CONSTRAINT `fk_livro_capa1`
    FOREIGN KEY (`id_capa`)
    REFERENCES `serpabooksdb`.`capa` (`id_capa`),
  CONSTRAINT `fk_livro_editora1`
    FOREIGN KEY (`id_editora`)
    REFERENCES `serpabooksdb`.`editora` (`id_editora`),
  CONSTRAINT `fk_livro_info_livro1`
    FOREIGN KEY (`id_info_livro`)
    REFERENCES `serpabooksdb`.`info_livro` (`id_info_livro`))
ENGINE = InnoDB
AUTO_INCREMENT = 483
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `serpabooksdb`.`preco_amazon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `serpabooksdb`.`preco_amazon` (
  `id_preco_amazon` BIGINT NOT NULL AUTO_INCREMENT,
  `preco_amazon` FLOAT NULL DEFAULT NULL,
  `img_amazon` VARCHAR(255) NULL DEFAULT NULL,
  `link_amazon` VARCHAR(500) NULL DEFAULT NULL,
  `dt_cadastro_preco_amazon` DATETIME NULL DEFAULT NULL,
  `id_livro` BIGINT NOT NULL,
  `id_capa` BIGINT NOT NULL,
  PRIMARY KEY (`id_preco_amazon`),
  INDEX `fk_preco_amazon_livro1` (`id_livro` ASC) VISIBLE,
  INDEX `fk_preco_amazon_capa1_idx` (`id_capa` ASC) VISIBLE,
  CONSTRAINT `fk_preco_amazon_capa1`
    FOREIGN KEY (`id_capa`)
    REFERENCES `serpabooksdb`.`capa` (`id_capa`),
  CONSTRAINT `fk_preco_amazon_livro1`
    FOREIGN KEY (`id_livro`)
    REFERENCES `serpabooksdb`.`livro` (`id_livro`))
ENGINE = InnoDB
AUTO_INCREMENT = 434
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `serpabooksdb`.`preco_magalu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `serpabooksdb`.`preco_magalu` (
  `id_preco_magalu` BIGINT NOT NULL AUTO_INCREMENT,
  `preco_magalu` FLOAT NULL DEFAULT NULL,
  `img_magalu` VARCHAR(255) NULL DEFAULT NULL,
  `link_magalu` VARCHAR(500) NULL DEFAULT NULL,
  `dt_cadastro_preco_magalu` DATETIME NULL DEFAULT NULL,
  `id_livro` BIGINT NOT NULL,
  PRIMARY KEY (`id_preco_magalu`),
  INDEX `fk_preco_magalu_livro1` (`id_livro` ASC) VISIBLE,
  CONSTRAINT `fk_preco_magalu_livro1`
    FOREIGN KEY (`id_livro`)
    REFERENCES `serpabooksdb`.`livro` (`id_livro`))
ENGINE = InnoDB
AUTO_INCREMENT = 242
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `serpabooksdb`.`preco_mercado_livre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `serpabooksdb`.`preco_mercado_livre` (
  `id_preco_mercado_livre` BIGINT NOT NULL AUTO_INCREMENT,
  `preco_mercado_livre` FLOAT NULL DEFAULT NULL,
  `img_mercado_livre` VARCHAR(255) NULL DEFAULT NULL,
  `link_mercado_livre` VARCHAR(2000) NULL DEFAULT NULL,
  `dt_cadastro_mercado_livre` DATETIME NULL DEFAULT NULL,
  `id_livro` BIGINT NOT NULL,
  PRIMARY KEY (`id_preco_mercado_livre`),
  INDEX `fk_preco_mercado_livre_livro1` (`id_livro` ASC) VISIBLE,
  CONSTRAINT `fk_preco_mercado_livre_livro1`
    FOREIGN KEY (`id_livro`)
    REFERENCES `serpabooksdb`.`livro` (`id_livro`))
ENGINE = InnoDB
AUTO_INCREMENT = 197
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
